### PR TITLE
fix(MessageDialog): Increased the font weight on the title and buttons

### PR DESCRIPTION
**Pull request by sethhaskellcondie**

### CODE REVIEW

**Comment by seanevd** [comment]
Is design asking you to introduce `font-weight: 600`?

**Comment by sethhaskellcondie** [comment]
I only have a screenshot from design, they want the title and button text to be more bold, when I change the font-weight to 600 in the developer tools of my browser it matches their screenshot.

**Comment by sethhaskellcondie** [comment]
So would it be better if I made a typography for the button text instead of just adding the font weight to the css?

**Comment by seanevd** [comment]
Is this a change needed for the extension? We recently lost font-weight 500 in the extension. Someone needs to do some work to figure out how to get it back. If there is a request to change font-weight, it probably stems from that issue. I would suggest fixing it in the extension before we start making new typography rules.

**Comment by seanevd** [comment]
I also just spoke with Jessie and he said he never approved (or was aware of) adding 600 to our type definitions.

**Comment by sethhaskellcondie** [comment]
I see, this is for the manager tool, and it is because of the missing 500 font weight as soon as that is fixed then that will fix this issue as well, so we don't need this change.  I've been working with Kellie Shelton instead of Jessie so it looks like we had a crossed wire there.

**Pull request closed without merging**
