### PR TITLE
fix(NewIcons): New Icons, colors, allow TextAreaInput to be styled.

### PR DESCRIPTION
**Pull request by cozzbp**

### CODE REVIEW

**Comment by seanevd** [comment]
You are opening up this component to allow any color?

**Comment by seanevd** [comment]
What is the reasoning behind this change?

**Comment by cozzbp** [comment]
Yeah, I'm just making it match the current TextInput component.  You can specify those props there as well.

**Comment by cozzbp** [comment]
I need it to be able to style it to work for the play creation screen:
image

**Comment by seanevd** [comment]
I like the idea of making a light and dark version better than allowing any color to come through.

**Comment by seanevd** [comment]
If we allow a custom lineColor then we lose those focus and disabled state colors?

**Comment by seanevd** [comment]
I guess not, but those colors might look strange on a green background, right?

**Comment by cozzbp** [comment]
I'd be open to a light and dark version at some point.  But for now I'm just making this component behave like the TextInput component.  I think it looks fine for now.
image

**Comment by cozzbp** [comment]
I'm trying to make this new separated play creator look as close to the old one as possible without doing a full redesign.  I'm just unwilling to pull in the super old school form stuff from the chrome app.

**Pull request merged**
