### PR TITLE
fix(colors): update colors to use new color palette from design

### PR DESCRIPTION
**Pull request by seanevd**

### CODE REVIEW

**Comment by seanevd** [comment]
This PR is mostly for the redesigned colors page, which includes the new color palette from design.
image

**Comment by seanevd** [comment]
If you don't use only design approved colors in the future, I'll destroy you.

**Comment by cozzbp** [comment]
@seanevd What about green00?  That was my most used color.

**Comment by seanevd** [comment]
@cozzbp it's with a sad heart I have to say we will no longer be able to use green00.

**Pull request merged**
