### PR TITLE
feat(MessageDialog): Add MessageDialog, ButtonBar, and update Button

### PR DESCRIPTION
**Pull request by cozzbp**
* Add MessageDialog Component
* Update Button Component
* Add ButtonBar Component

### CODE REVIEW

**Comment by cozzbp** [comment]
Yeah that's why I'm bringing them in.

**Comment by seanevd** [comment]
We should remember to import these components to the extension and manager app whenever we need them in the future and remove them from the extension so we don't have two different versions.

**Comment by cozzbp** [comment]
Yeah we could add a story to replace all of these in the extension.  One where that would be difficult is the messagedialog though :(  Unfortunately in the extension it has that close extension button hacked in to be able to minimize the app and close the modal.

**Comment by seanevd** [comment]
We could probably remove all of the duplicate logic from the existing component (in the extension) and import this component there, but keep the minimize stuff. Then we don't need to add a new import statement to every file that needs this modal.

**Comment by cozzbp** [comment]
Ah good call, that sounds like a plan.

**Pull request merged**
